### ISSUE TITLE
Is this accessing the docker daemon on the build node?

### ISSUE THREAD

**Issue by jwalters-gpsw** [deis/dockerbuilder#110]
More of a question than an issue. I'm trying to understand if this image is directly accessing the docker daemon on the k8s worker node. How is that possible without elevated privs?

**Comment by bacongobbler** [comment]
Privileged mode is only required to run docker in docker. Since we're just mounting in the socket via [volume mounts](https://github.com/deis/builder/blob/676665ce4c29a050ffc8126da1142a9630ebeb54/pkg/gitreceive/k8s_util.go#L77-L80), we're just using the client to talk to the host so no privilege escalation is required.

**Comment by jwalters-gpsw** [comment]
Thanks. Got it.
